image: docker.elastic.co/beats/filebeat
imageTag: 7.13.2
nameOverride: ""
namespaceOverride: ""
fullnameOverride: filebeat

apiVersions:
  configMap: v1
  daemonset: apps/v1
  clusterRoleBinding: rbac.authorization.k8s.io/v1
  clusterRole: rbac.authorization.k8s.io/v1
  serviceAccount: v1
  secret: v1

managedServiceAccount: true

clusterRoleRules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list

logzioCert:
  SectigoRSADomainValidationSecureServerCA.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
    iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
    cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
    BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
    MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
    BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
    ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
    VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
    TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
    eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
    oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
    Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
    uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
    BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
    +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
    CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
    LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
    BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
    bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
    L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
    ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
    7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
    H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
    RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
    xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
    sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
    l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
    6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
    LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
    yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
    00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
    -----END CERTIFICATE-----

configType: standard

filebeatConfig:
  standardConfig:
    filebeat.yml: |-
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
          - /var/lib/docker/containers/*/*.log
        exclude_files:
          - /var/lib/docker/containers/.*/container-cached.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"
          - add_cloud_metadata: ~
          - add_docker_metadata: 
          - rename:
              fields:
                - from: agent
                  to: beat_agent
              ignore_missing: true
          - rename:
              fields:
                - from: log.file.path
                  to: source
              ignore_missing: true
          # Drop ECS Logging Agent
          - drop_event:
              when:
                or:
                  - contains:
                      container.name: filebeat
                  - contains:
                      container.name: ecs-agent
          # Drop K8S Logging Agent
          - drop_event:
              when:
                or:
                  - equals:
                      kubernetes.namespace: filebeat
          # Drop PID Events (K8S and ECS)
          - drop_event:
              when:
                or:
                  - contains:
                      message: "PID"
                  - contains:
                      message: "pid"
                  - contains:
                      messsage: "IP 127.0.0.1"
                  - contains:
                      message: "ping provider status:200"
                  - contains:
                      message: "ping provider status:401"
          # Drop Health Checks
          - drop_event:
              when:
                or:
                  - contains:
                      message: "ELB-HealthChecker/2.0"
                  - contains:
                      message: "/v1/health"
                  - contains:
                      message: "healcheck"
                  - contains:
                      message: "healthcheck"
                  - contains:
                      message: "health check"
                  - contains:
                      message: "Healthcheck"
                  - contains:
                      message: "Health check"
                  - contains:
                      message: "Health Check"
                  - contains:
                      message: "health-check"
                  - contains:
                      message: "/health"
                  - contains:
                      message: "HealthModule dependencies initialized"
                  - contains:
                      message: "HealthModule"
          # Drop Unuseful K8S Info
          - drop_event:
              when:
                or:
                  - equals:
                      kubernetes.namespace: argocd
                  - equals:
                      kubernetes.namespace: argocd-image-updater
                  - equals:
                      kubernetes.namespace: argocd-rollouts
                  - equals:
                      kubernetes.namespace: kube-system
                  - equals:
                      kubernetes.namespace: default
                  - equals:
                      kubernetes.namespace: external-dns
                  - equals:
                      kubernetes.namespace: external-secrets
                  - equals:
                      kubernetes.namespace: flagger-system
                  - equals:
                      kubernetes.namespace: flux-system
                  - equals:
                      kubernetes.namespace: guestbook
                  - equals:
                      kubernetes.namespace: istio-system
                  - equals:
                      kubernetes.namespace: kube-node-lease
                  - equals:
                      kubernetes.namespace: kube-public
                  - equals:
                      kubernetes.namespace: node-problem-detector
                  - equals:
                      kubernetes.namespace: test-oki
                  - equals:
                      kubernetes.namespace: karpenter
                  - equals:
                      kubernetes.namespace: newrelic
                  - equals:
                      kubernetes.namespace: ingress-nginx
                  - equals:
                      kubernetes.namespace: atlantis
          # Drop BB Worker ECS
          - drop_event:
              when:
                and:
                  - contains:
                      container.name: ecs-bb-adapter-worker
                  - or:
                      - contains:
                          message: "called method"
                      - contains:
                          message: "external request"
                      - contains:
                          message: "InstantPaymentConfirmationSQSPort"
                      - contains:
                          message: "requeuing"
          # Drop BB Worker K8S
          - drop_event:
              when:
                and:
                  - contains:
                      kubernetes.container.name: bb-adapter-worker
                  - or:
                      - contains:
                          message: "called method"
                      - contains:
                          message: "external request"
                      - contains:
                          message: "InstantPaymentConfirmationSQSPort"
                      - contains:
                          message: "requeuing"
          # Drop Filters Logz.io (Dev)
          # - drop_event:
          #     when:
          #       and:
          #       - equals:
          #           kubernetes.container.name: transactions-worker-dev
          #        - or:
          #            - equals:
          #               SeverityText: DEBUG
          #            - equals:
          #               SeverityText: ERROR
          - drop_event:
              when:
                and:
                  - equals:
                      kubernetes.container.name: transactions-dev
                  - equals:
                      SeverityText: DEBUG
          - drop_event:
              when:
                and:
                  - equals:
                      kubernetes.container.name: webhooks-nt-dev
                  - or:
                      - equals:
                          SeverityText: INFO
                      - equals:
                          SeverityText: DEBUG
          - drop_event:
              when:
                or:
                    # - equals:
                    #     SeverityText: INFO
                    # - equals:
                    #     SeverityText: DEBUG
                    - equals:
                        SeverityText: TRACE
                    # - equals:
                    #     SeverityText: ERROR
          # Unecessary log fields.
          # Container info
          - drop_fields:
              fields: ["container.id", "container.runtime", "input.type"]
              ignore_missing: true
          # Kubernetes info
          - drop_fields:
              fields: ["kubernetes.labels.app_kubernetes_io/instance", "kubernetes.labels.app_kubernetes_io/name", "kubernetes.labels.pod-template-hash", "kubernetes.namespace_labels.kubernetes_io/metadata_name", "kubernetes.namespace_uid", "kubernetes.node.labels.beta_kubernetes_io/arch", "kubernetes.node.labels.beta_kubernetes_io/instance-type", "kubernetes.node.labels.beta_kubernetes_io/os", "kubernetes.node.labels.eks_amazonaws_com/nodegroup-image", "kubernetes.node.labels.eks_amazonaws_com/sourceLaunchTemplateId", "kubernetes.node.labels.eks_amazonaws_com/sourceLaunchTemplateVersion", "kubernetes.node.labels.k8s_io/cloud-provider-aws", "kubernetes.node.labels.kubernetes_io/arch", "kubernetes.node.labels.kubernetes_io/hostname", "kubernetes.node.labels.kubernetes_io/os", "kubernetes.node.labels.eks_amazonaws_com/capacityType", "kubernetes.node.labels.topology_ebs_csi_aws_com/zone", "kubernetes.node.labels.failure-domain_beta_kubernetes_io/region", "kubernetes.node.labels.failure-domain_beta_kubernetes_io/zone", "kubernetes.node.hostname", "kubernetes.node.uid", "kubernetes.pod.ip", "kubernetes.pod.uid", "kubernetes.replicaset.name"]
              ignore_missing: true
          - dissect:
              tokenizer: "%{name}:%{version}"
              field: "container.image.name"
              target_prefix: "container.image."
      fields:
        logzio_codec: ${LOGZIO_CODEC}
        token: ${LOGZIO_LOGS_SHIPPING_TOKEN}
        cluster: ${CLUSTER_NAME}
        type: ${LOGZIO_TYPE}
        
      fields_under_root: ${FIELDS_UNDER_ROOT}
      ignore_older: ${IGNORE_OLDER}
      registry_file: /var/lib/filebeat/registry
      output:
        logstash:
          hosts: ["${LOGZIO_LOGS_LISTENER_HOST}:5015"]
          ssl:
            certificate_authorities: ['/etc/pki/tls/certs/SectigoRSADomainValidationSecureServerCA.crt']

serviceAccount:
  create: true
  name: filebeat

terminationGracePeriod: 30
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

daemonset:
  ignoreOlder: 3h
  logzioCodec: json
  logzioType: filebeat
  fieldsUnderRoot: true
  securityContext:
    runAsUser: 0
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations: {}
  priorityClassName: ""
  volumes:
    - name: cert
      configMap:
        defaultMode: 384
        name: logzio-logs-cert
    - name: config
      configMap:
        defaultMode: 416
        name: filebeat-config
  volumeMounts:
    - name: config
      mountPath: /etc/filebeat.yml
      readOnly: true
      subPath: filebeat.yml
    - name: cert
      mountPath: /etc/pki/tls/certs/SectigoRSADomainValidationSecureServerCA.crt
      readOnly: true
      subPath: SectigoRSADomainValidationSecureServerCA.crt

secrets:
  create: true
  logzioShippingToken: ""
  logzioRegion: " "
  clusterName: ""
